// Supabase Edge Function: send-otp
// Generated by Antigravity

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.6";
import { createTransport } from "npm:nodemailer@6.9.8";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { email, purpose } = await req.json();

    if (!email || !purpose) {
      return new Response(
        JSON.stringify({ error: "Missing email or purpose" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // Validate email constraints based on purpose
    const { data: userExists, error: checkError } = await supabaseAdmin.rpc("check_user_exists", {
      email_to_check: email,
    });
    if (checkError) throw checkError;

    if (purpose === "reset" && !userExists) {
      return new Response(
        JSON.stringify({ error: "No account registered with this email." }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (purpose === "signup" && userExists) {
      return new Response(
        JSON.stringify({ error: "An account is already registered with this email." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 1. Generate random 6-digit OTP
    const otp = Math.floor(100000 + Math.random() * 900000).toString();
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes expiry

    // 2. Invalidate any previous OTPs for this email and purpose
    await supabaseAdmin
      .from("otp_verifications")
      .update({ is_verified: true })
      .eq("email", email)
      .eq("purpose", purpose);

    // 3. Save the new OTP code
    const { error: dbError } = await supabaseAdmin.from("otp_verifications").insert({
      email,
      otp_code: otp,
      purpose,
      expires_at: expiresAt.toISOString(),
    });

    if (dbError) throw dbError;

    // 4. Load SMTP credentials from environment
    const smtpHost = Deno.env.get("SMTP_HOST") ?? "smtp.gmail.com";
    const smtpPort = parseInt(Deno.env.get("SMTP_PORT") ?? "587", 10);
    const smtpUser = Deno.env.get("SMTP_USER") ?? "";
    const smtpPass = Deno.env.get("SMTP_PASS") ?? "";
    const smtpFrom = Deno.env.get("SMTP_FROM") ?? smtpUser;

    if (!smtpUser || !smtpPass) {
      throw new Error("SMTP credentials are not configured in environment variables.");
    }

    const transporter = createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: { user: smtpUser, pass: smtpPass },
    });

    const subject = purpose === "signup" ? "Verify your PawPing Account" : "Reset your PawPing Password";
    const titleText = purpose === "signup" ? "Welcome to PawPing!" : "Reset Your Password";
    const bodyText = purpose === "signup" 
      ? "Thank you for joining PawPing. Use the code below to verify your email address and activate your account:" 
      : "We received a request to reset your PawPing account password. Use the code below to complete the reset:";

    const emailHtml = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 500px; margin: 0 auto; padding: 30px; border: 1px solid #eef2f6; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.03);">
        <div style="text-align: center; margin-bottom: 24px;">
          <h1 style="color: #FF7A59; margin: 0; font-size: 28px; font-weight: 800; letter-spacing: -0.5px;">PawPing</h1>
        </div>
        <h2 style="color: #1a1f36; font-size: 20px; font-weight: 700; margin-bottom: 12px; text-align: center;">${titleText}</h2>
        <p style="color: #4f566b; font-size: 15px; line-height: 1.5; margin-bottom: 24px; text-align: center;">${bodyText}</p>
        <div style="text-align: center; margin: 32px 0;">
          <span style="font-size: 36px; font-weight: 800; letter-spacing: 6px; color: #1a1f36; background-color: #f7fafc; padding: 12px 28px; border-radius: 12px; border: 1px solid #e3e8ee; display: inline-block;">${otp}</span>
        </div>
        <p style="color: #a3acb9; font-size: 13px; text-align: center; line-height: 1.4; margin-top: 24px;">This code is valid for 10 minutes. For security, please do not share this code with anyone.</p>
        <hr style="border: 0; border-top: 1px solid #e3e8ee; margin: 24px 0;" />
        <p style="color: #a3acb9; font-size: 12px; text-align: center; margin: 0;">© 2026 PawPing App. All rights reserved.</p>
      </div>
    `;

    await transporter.sendMail({
      from: `"PawPing Security" <${smtpFrom}>`,
      to: email,
      subject,
      html: emailHtml,
    });

    return new Response(
      JSON.stringify({ success: true, message: "OTP sent successfully" }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
