// Supabase Edge Function: reset-password
// Generated by Antigravity

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.6";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { email, code, new_password } = await req.json();

    if (!email || !code || !new_password) {
      return new Response(
        JSON.stringify({ error: "Missing email, code, or password" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // 1. Verify that this OTP code was successfully verified recently (within the last 15 minutes)
    const fifteenMinutesAgo = new Date(Date.now() - 15 * 60 * 1000).toISOString();
    const { data: record, error: dbError } = await supabaseAdmin
      .from("otp_verifications")
      .select("*")
      .eq("email", email)
      .eq("purpose", "reset")
      .eq("otp_code", code)
      .eq("is_verified", true)
      .gt("created_at", fifteenMinutesAgo)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (dbError) throw dbError;

    if (!record) {
      return new Response(
        JSON.stringify({ error: "Verification session has expired or is invalid. Please request a new code." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 2. Retrieve user ID for the given email
    const { data: userId, error: idError } = await supabaseAdmin.rpc("get_user_id_by_email", {
      email_to_find: email,
    });

    if (idError || !userId) {
      return new Response(
        JSON.stringify({ error: "No user account was found associated with this email address." }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 3. Update the user password using Supabase Auth Admin API
    const { error: updateError } = await supabaseAdmin.auth.admin.updateUserById(userId, {
      password: new_password,
    });

    if (updateError) throw updateError;

    // 4. Invalidate/Delete the OTP verification record so it cannot be used again
    await supabaseAdmin
      .from("otp_verifications")
      .delete()
      .eq("id", record.id);

    return new Response(
      JSON.stringify({ success: true, message: "Password updated successfully." }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
