// Supabase Edge Function: verify-otp
// Generated by Antigravity

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.6";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { email, code, purpose } = await req.json();

    if (!email || !code || !purpose) {
      return new Response(
        JSON.stringify({ error: "Missing email, code, or purpose" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // 1. Find the latest valid OTP verification code
    const { data: record, error: dbError } = await supabaseAdmin
      .from("otp_verifications")
      .select("*")
      .eq("email", email)
      .eq("purpose", purpose)
      .eq("otp_code", code)
      .eq("is_verified", false)
      .gt("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (dbError) throw dbError;

    if (!record) {
      return new Response(
        JSON.stringify({ error: "Invalid or expired verification code." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 2. Mark the OTP code as verified
    const { error: updateError } = await supabaseAdmin
      .from("otp_verifications")
      .update({ is_verified: true })
      .eq("id", record.id);

    if (updateError) throw updateError;

    return new Response(
      JSON.stringify({ success: true, verified: true, message: "OTP verified successfully." }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
